---
#write here the world name where you want InventoryCommand works!
#set this field empty if you want that works on all worlds in the server
#if you want to apply only on two or more worlds, enter the names of the worlds separated by a comma
#example level: world, hungergames, lobby
level: world


data:
  #write here slot + slot number (max of slots allowed 35)
  slot1:
    #write here item ID
    id: 46
    #write here item damage
    damage: 0
    #write here item amount
    amount: 64
    command:
      -
      -
      -
  slot2:
    id: 0
    damage: 0
    amount: 0
    command:
      -
      -
      -
#you can add more item,max is 35. Also you can add infinite commands!
...
